YAML
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Обратите внимание на отступ
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "gpt4free" # Обновлять только gpt4free
